name: 'spring-boot-microservices-bookstore'
services:
  catalog-db:
    image: postgres:16-alpine
#    container-name: catalog-db
    environment:
      - POSTGRES_USER={postgres_user}
      - POSTGRES_PASSWORD={postgres_password}
      - POSTGRES_DB={postgres_db}
    ports:
      - "15432:5432"
    healthcheck:
#      `pg_isready` is a utility provided with PostgreSQL to check the connection status of a PostgreSQL server.
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  order-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER={postgres_user}
      - POSTGRES_PASSWORD={postgres_password}
      - POSTGRES_DB={postgres_db}
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bookstore-rabbitmq:
    image: rabbitmq:3.12.11-management
    environment:
      - RABBITMQ_DEFAULT_USER={mq_user}
      - RABBITMQ_DEFAULT_PASS={mq_pass}
    ports:
      - "5672:5672"
      -  "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m