name: 'spring-boot-microservices-bookstore'
services:
  catalog-db:
    image: postgres:16-alpine
#    container-name: catalog-db
    environment:
      - POSTGRES_USER={postgres_user}
      - POSTGRES_PASSWORD={postgres_password}
      - POSTGRES_DB={postgres_db}
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg-isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m