name: Catalog Service

on:
#  To trigger on push
  push:
#    To trigger on push in this path
    paths:
      - catalog-service/**
#    To trigger on push in this path on the following branch
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
#      Since catalog service is not the root project, we are setting the working directory here
      working-directory: ./catalog-service
#    Here we are setting the environment for this pipeline
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
#    The following are the build steps
    steps:
#      Checkout the code
      - name: Checkout latest code
        uses: actions/checkout@v4

#      Setting up java
#      The following is the name of the step shown in the github screen
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
#          This is done so that the first time the dependencies are downloaded and cached for subsequent runs
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify